//! libfs: nested read-only tree mounted at `/lib/…` (newlib sysroot).
//!
//! Paths are relative to the mount, e.g. `newlib/include/unistd.h`,
//! `newlib/lib/libc.a`. Directories are implied by children.

use alloc::string::String;
use alloc::vec::Vec;
use spin::Mutex;

use crate::fs::StatInfo;

const PATH_CAP: usize = 96;
const MAX_FILES: usize = 2048;

const S_IFDIR: u32 = 0o040000;
const S_IFREG: u32 = 0o100000;

struct File {
    path: String,
    data: &'static [u8],
}

static FILES: Mutex<Vec<File>> = Mutex::new(Vec::new());

fn valid_rel(path: &str) -> bool {
    !path.is_empty()
        && path.len() <= PATH_CAP
        && !path.starts_with('/')
        && !path.ends_with('/')
        && !path.contains("//")
}

pub fn register(name: &str, bytes: &'static [u8]) -> bool {
    if !valid_rel(name) {
        return false;
    }
    let mut files = FILES.lock();
    if let Some(e) = files.iter_mut().find(|e| e.path == name) {
        e.data = bytes;
        return true;
    }
    if files.len() >= MAX_FILES {
        return false;
    }
    files.push(File {
        path: String::from(name),
        data: bytes,
    });
    true
}

pub fn lookup(name: &str) -> Option<&'static [u8]> {
    if !valid_rel(name) {
        return None;
    }
    let files = FILES.lock();
    files.iter().find(|e| e.path == name).map(|e| e.data)
}

pub fn create(_name: &str) -> bool {
    false
}

pub fn truncate(_name: &str) -> bool {
    false
}

pub fn read(name: &str, pos: usize, out: &mut [u8]) -> usize {
    let Some(data) = lookup(name) else {
        return 0;
    };
    let n = out.len().min(data.len().saturating_sub(pos));
    if n != 0 {
        out[..n].copy_from_slice(&data[pos..pos + n]);
    }
    n
}

pub fn write(_name: &str, _pos: usize, _buf: &[u8]) -> Option<usize> {
    None
}

fn is_dir_path(files: &[File], dir: &str) -> bool {
    if dir.is_empty() {
        return true;
    }
    files.iter().any(|e| {
        e.path == dir
            || (e.path.starts_with(dir) && e.path.as_bytes().get(dir.len()) == Some(&b'/'))
    })
}

pub fn listdir_at(rel: &str, buf: &mut [u8]) -> usize {
    let dir = if rel.is_empty() || rel == "." {
        ""
    } else if valid_rel(rel) {
        rel
    } else {
        return 0;
    };
    let files = FILES.lock();
    if !dir.is_empty() && !is_dir_path(&files, dir) {
        return 0;
    }
    let mut n = 0;
    let mut seen: Vec<&str> = Vec::new();
    for e in files.iter() {
        let child = if dir.is_empty() {
            match e.path.split_once('/') {
                Some((head, _)) => head,
                None => e.path.as_str(),
            }
        } else if e.path.starts_with(dir)
            && e.path.as_bytes().get(dir.len()) == Some(&b'/')
        {
            let rest = &e.path[dir.len() + 1..];
            match rest.split_once('/') {
                Some((head, _)) => head,
                None => rest,
            }
        } else {
            continue;
        };
        if seen.iter().any(|s| *s == child) {
            continue;
        }
        seen.push(child);
        let name = child.as_bytes();
        let need = name.len() + 1;
        if n + need > buf.len() {
            break;
        }
        buf[n..n + name.len()].copy_from_slice(name);
        n += name.len();
        buf[n] = b'\n';
        n += 1;
    }
    n
}

pub fn stat(name: &str) -> Option<StatInfo> {
    if name.is_empty() || name == "." || name == ".." {
        return Some(StatInfo {
            mode: S_IFDIR | 0o755,
            size: 0,
            ino: 1,
            nlink: 2,
        });
    }
    if !valid_rel(name) {
        return None;
    }
    let files = FILES.lock();
    if let Some((i, e)) = files.iter().enumerate().find(|(_, e)| e.path == name) {
        return Some(StatInfo {
            mode: S_IFREG | 0o444,
            size: e.data.len() as u32,
            ino: (i as u32) + 2,
            nlink: 1,
        });
    }
    if is_dir_path(&files, name) {
        return Some(StatInfo {
            mode: S_IFDIR | 0o755,
            size: 0,
            ino: 1,
            nlink: 2,
        });
    }
    None
}

/// Register packed newlib sysroot generated by `kernel/build.rs`.
pub fn init_embedded() {
    lib_embed::register_all();
}

mod lib_embed {
    include!(concat!(env!("OUT_DIR"), "/lib_embed.rs"));
}
