//! sbasefs: read-only flat namespace for cross-built suckless sbase ELFs at `/s/…`.

use spin::Mutex;

use crate::console;
use crate::fs::StatInfo;

const MAX_FILES: usize = 128;
const NAME_CAP: usize = 32;

#[derive(Clone, Copy)]
struct Slot {
    name: [u8; NAME_CAP],
    len: usize,
    data: &'static [u8],
}

static FILES: Mutex<[Option<Slot>; MAX_FILES]> = Mutex::new([None; MAX_FILES]);

pub fn register(name: &str, bytes: &'static [u8]) -> bool {
    if name.is_empty() || name.contains('/') {
        return false;
    }
    let len = name.len().min(NAME_CAP);
    let mut n = [0u8; NAME_CAP];
    n[..len].copy_from_slice(&name.as_bytes()[..len]);

    let mut files = FILES.lock();
    for slot in files.iter_mut() {
        if let Some(s) = slot {
            if s.len == len && s.name[..len] == n[..len] {
                s.data = bytes;
                log_reg(name, bytes.len(), true);
                return true;
            }
        }
    }
    for slot in files.iter_mut() {
        if slot.is_none() {
            *slot = Some(Slot {
                name: n,
                len,
                data: bytes,
            });
            log_reg(name, bytes.len(), false);
            return true;
        }
    }
    console::status_progress(&alloc::format!("sbasefs full (cannot register {name})"));
    false
}

pub fn lookup(name: &str) -> Option<&'static [u8]> {
    if name.is_empty() || name == "." || name == ".." {
        return None;
    }
    let files = FILES.lock();
    for slot in files.iter().flatten() {
        if slot.len == name.len() && &slot.name[..slot.len] == name.as_bytes() {
            return Some(slot.data);
        }
    }
    None
}

pub fn listdir_at(rel: &str, buf: &mut [u8]) -> usize {
    if !rel.is_empty() && rel != "." {
        return 0;
    }
    listdir(buf)
}

pub fn listdir(buf: &mut [u8]) -> usize {
    let files = FILES.lock();
    let mut n = 0;
    for slot in files.iter().flatten() {
        let name = &slot.name[..slot.len];
        let need = name.len() + 1;
        if n + need > buf.len() {
            break;
        }
        buf[n..n + name.len()].copy_from_slice(name);
        n += name.len();
        buf[n] = b'\n';
        n += 1;
    }
    n
}

pub fn count() -> usize {
    FILES.lock().iter().flatten().count()
}

const S_IFDIR: u32 = 0o040000;
const S_IFREG: u32 = 0o100000;

pub fn stat(name: &str) -> Option<StatInfo> {
    if name.is_empty() || name == "." || name == ".." {
        return Some(StatInfo {
            mode: S_IFDIR | 0o755,
            size: 0,
            ino: 1,
            nlink: 2,
        });
    }
    let files = FILES.lock();
    for (i, slot) in files.iter().flatten().enumerate() {
        if slot.len == name.len() && &slot.name[..slot.len] == name.as_bytes() {
            return Some(StatInfo {
                mode: S_IFREG | 0o555,
                size: slot.data.len() as u32,
                ino: (i as u32) + 2,
                nlink: 1,
            });
        }
    }
    None
}

fn log_reg(name: &str, n: usize, replace: bool) {
    let kind = if replace { "replace" } else { "new" };
    console::status_progress(&alloc::format!("sbase {kind} {name} ({n} bytes)"));
}

/// Register embedded sbase ELFs generated by `kernel/build.rs`.
pub fn init_embedded() {
    sbase_embed::register_all();
}

mod sbase_embed {
    include!(concat!(env!("OUT_DIR"), "/sbase_embed.rs"));
}
