#!/usr/bin/env bash
# Cross-build the upstream sbase utilities with newlib + myos libgloss, as
# one multicall ELF (target/sbase-<arch>-unknown-none) and the manifest of
# its names, which the image hard-links to it under /bin/sbase.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=scripts/myos-c-userspace-lib.sh
source "$ROOT/scripts/myos-c-userspace-lib.sh"

if myos_sbase_is_current; then
  echo "sbase ELFs up to date"
  exit 0
fi

"$ROOT/ports/sbase/prepare.sh"
# sbase compiles newlib's regex sources (REGEX_SRCS) directly from the
# newlib source tree, so the source must be present even when newlib
# *outputs* are cached (CI pulls them from GHCR and build.sh exits early).
# fetch.sh is idempotent and cheap when the tree already exists.
"$ROOT/toolchain/newlib/fetch.sh"
"$ROOT/toolchain/newlib/build.sh"
export PATH="$ROOT/target/newlib-bin:$PATH"

WORK="$ROOT/target/sbase-myos-build"
BINS_FILE="$ROOT/ports/sbase/bins.txt"
SBASE_BINS=()
while IFS= read -r line; do SBASE_BINS+=("$line"); done <"$BINS_FILE"

CPPFLAGS=(
  -DPREFIX=\"/bin\"
  -D_DEFAULT_SOURCE
  -D_GNU_SOURCE
  -D_NETBSD_SOURCE
  -D_BSD_SOURCE
  -D_XOPEN_SOURCE=700
  -D_FILE_OFFSET_BITS=64
  -I"$WORK"
  -I"$ROOT/ports/sbase"
  -include myos_compat.h
  -include sys/myos_extra.h
  -Wno-implicit-function-declaration
)

LIBUTIL_SRCS=(
  libutil/concat.c libutil/cp.c libutil/crypt.c libutil/confirm.c libutil/ealloc.c
  libutil/enmasse.c libutil/eprintf.c libutil/eregcomp.c libutil/estrtod.c
  libutil/fnck.c libutil/fshut.c libutil/getlines.c libutil/human.c libutil/linecmp.c
  libutil/md5.c libutil/memmem.c libutil/mkdirp.c libutil/mode.c libutil/parseoffset.c
  libutil/putword.c libutil/reallocarray.c libutil/recurse.c libutil/rm.c
  libutil/sha1.c libutil/sha224.c libutil/sha256.c libutil/sha384.c libutil/sha512.c
  libutil/sha512-224.c libutil/sha512-256.c libutil/strcasestr.c libutil/strlcat.c
  libutil/strlcpy.c libutil/strsep.c libutil/strnsubst.c libutil/strtonum.c
  libutil/unescape.c libutil/writeall.c
)

LIBUTF_SRCS=(
  libutf/fgetrune.c libutf/fputrune.c libutf/isalnumrune.c libutf/isalpharune.c
  libutf/isblankrune.c libutf/iscntrlrune.c libutf/isdigitrune.c libutf/isgraphrune.c
  libutf/isprintrune.c libutf/ispunctrune.c libutf/isspacerune.c libutf/istitlerune.c
  libutf/isxdigitrune.c libutf/lowerrune.c libutf/rune.c libutf/runetype.c
  libutf/upperrune.c libutf/utf.c libutf/utftorunestr.c
)

REGEX_SRCS=(
  posix/regcomp.c posix/regerror.c posix/regexec.c posix/regfree.c
  posix/collate.c posix/collcmp.c posix/fnmatch.c
)

compile() {
  local cc="$1"
  local inc="$2"
  local src="$3"
  local out="$4"
  shift 4
  "$cc" -ffreestanding -fPIC -O2 -isystem "$inc" "${CPPFLAGS[@]}" "$@" -c "$src" -o "$out"
}

# The C identifier of a tool's main: sbase_<name>_main, dashes as
# underscores (sha512-224sum).
main_of() {
  local name="${1//-/_}"
  echo "sbase_${name}_main"
}

# The dispatcher of the multicall ELF: runs the tool named by argv[0]'s last
# component (every name is a hard link to the one ELF), like upstream's
# sbase-box (scripts/mkbox), with the names of bins.txt.
write_box() {
  local out="$1"
  shift
  local name
  {
    echo '/* Generated by ports/sbase/build.sh: every sbase tool in one ELF. */'
    echo '#include <stdio.h>'
    echo '#include <string.h>'
    echo
    for name in "$@"; do echo "int $(main_of "$name")(int, char **);"; done
    echo
    echo 'static const struct {'
    echo '	const char *name;'
    echo '	int (*fn)(int, char **);'
    echo '} cmds[] = {'
    for name in "$@"; do echo "	{\"$name\", $(main_of "$name")},"; done
    echo '};'
    echo
    echo 'int'
    echo 'main(int argc, char *argv[])'
    echo '{'
    echo '	const char *s = argc > 0 && argv[0] ? argv[0] : "";'
    echo '	const char *slash = strrchr(s, '"'"'/'"'"');'
    echo '	size_t i;'
    echo
    echo '	if (slash)'
    echo '		s = slash + 1;'
    echo '	for (i = 0; i < sizeof(cmds) / sizeof(cmds[0]); i++)'
    echo '		if (strcmp(cmds[i].name, s) == 0)'
    echo '			return cmds[i].fn(argc, argv);'
    echo '	fputs("sbase: not a tool name: ", stderr);'
    echo '	fputs(s, stderr);'
    echo '	fputc('"'"'\n'"'"', stderr);'
    echo '	return 127;'
    echo '}'
  } >"$out"
}

build_arch() {
  local arch="$1"
  local triple="${arch}-unknown-myos"
  local prefix="$ROOT/target/newlib-${arch}"
  local inc="$prefix/${triple}/include"
  local lib="$prefix/${triple}/lib"
  local cc="${triple}-cc"
  local objdir="$ROOT/target/sbase-obj-${arch}"
  local manifest="$ROOT/target/sbase-manifest-${arch}.txt"
  local out="$ROOT/target/sbase-${arch}-unknown-none"
  local myos="$ROOT/ports/sbase"
  local names=()
  local failed=()

  rm -rf "$objdir"
  mkdir -p "$objdir"
  rm -f "$manifest" "$out"

  local objs=()
  local src base obj
  for src in "${LIBUTIL_SRCS[@]}" "${LIBUTF_SRCS[@]}"; do
    base="$(basename "$(dirname "$src")")-$(basename "$src" .c)"
    obj="$objdir/${base}.o"
    compile "$cc" "$inc" "$WORK/$src" "$obj"
    objs+=("$obj")
  done
  for src in "${REGEX_SRCS[@]}"; do
    obj="$objdir/regex-$(basename "$src" .c).o"
    compile "$cc" "$inc" "$ROOT/target/newlib-src/newlib/libc/$src" "$obj"
    objs+=("$obj")
  done

  if [[ "$arch" == "aarch64" ]]; then
    compile "$cc" "$inc" "$myos/trunctfdf2.c" "$objdir/trunctfdf2.o"
    objs+=("$objdir/trunctfdf2.o")
  elif [[ "$arch" == "riscv64" ]]; then
    compile "$cc" "$inc" "$myos/riscv64-softfloat.c" "$objdir/riscv64-softfloat.o"
    objs+=("$objdir/riscv64-softfloat.o" "$(myos_riscv64_softfloat)")
  fi

  # Each tool's main renamed for the dispatcher. A tool that does not
  # compile (bc without bison) is left out, not fatal.
  local name
  for name in "${SBASE_BINS[@]}"; do
    [[ -n "$name" && "$name" != \#* ]] || continue
    if [[ ! -f "$WORK/${name}.c" ]]; then
      failed+=("$name:no-source")
      continue
    fi
    obj="$objdir/prog-${name}.o"
    if ! compile "$cc" "$inc" "$WORK/${name}.c" "$obj" -Dmain="$(main_of "$name")"; then
      failed+=("$name:compile")
      continue
    fi
    objs+=("$obj")
    names+=("$name")
  done
  if ((${#names[@]} == 0)); then
    echo "error: no sbase tool compiled for ${arch}" >&2
    exit 1
  fi

  write_box "$objdir/box.c" "${names[@]}"
  compile "$cc" "$inc" "$objdir/box.c" "$objdir/box.o"
  objs+=("$objdir/box.o")

  "${triple}-ld" -pie --no-dynamic-linker -o "$out" \
    --entry=_start -z max-page-size=4096 \
    "$lib/crt0.o" "${objs[@]}" -L"$lib" \
    --start-group -lc -lgloss -lg --end-group
  "${triple}-strip" -s "$out"
  printf '%s\n' "${names[@]}" >"$manifest"

  echo "sbase ${arch}: ${#names[@]}/${#SBASE_BINS[@]} tools in $(basename "$out") ($(du -h "$out" | cut -f1))"
  if ((${#failed[@]} > 0)); then
    printf '  left out: %s\n' "${failed[@]}" >&2
  fi
}

for arch in x86_64 aarch64 riscv64; do
  build_arch "$arch"
done

echo "$(myos_sbase_version_hash)" >"$MYOS_SBASE_VERSION"
