[workspace]

[package]
name = "dns"
version = "0.1.0"
edition = "2024"
publish = false
description = "DNS resolution via Plan 9 /net/udp (netd)."

[[bin]]
name = "dns"
test = false
bench = false

[dependencies]
myos-user = { path = "../lib" }

[profile.dev]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"

[profile.release]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"