[workspace]

[package]
name = "ping"
version = "0.1.0"
edition = "2024"
publish = false
description = "ICMP echo to a dotted IPv4 via Plan 9 /net/icmp (netd)."

[[bin]]
name = "ping"
test = false
bench = false

[dependencies]
myos-user = { path = "../lib" }

[profile.dev]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"

[profile.release]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"
