[workspace]

[package]
name = "ok"
version = "0.1.0"
edition = "2024"
publish = false
description = "Slim always-on boot smoke: alloc, /msg, disk/FAT listdir; no heavy carnival."

[[bin]]
name = "ok"
test = false
bench = false

[dependencies]
myos-user = { path = "../lib" }

[profile.dev]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"

[profile.release]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"
