//! xHCI: the USB host controller module (`docs/usb.md`).
//!
//! Finds the controllers by PCI class (`0x0C/0x03`, programming interface
//! `0x30`), brings them up (`hc`), and publishes the USB bus as the service
//! [`USB_SERVICE`]: a [`UsbHostOps`] table the class driver modules
//! (`usb_hub`, `usb_storage`) drive devices through. Enumeration, hot-plug
//! and the drivers' hooks run on one kernel thread (`thread_main`); the
//! interrupt handler only consumes the event ring (`hc::process_events`).
//! The hubs below the root ports are a class driver's business (`usb_hub`)
//! that hands children back through `hub_attach`.

#![no_std]
#![no_main]
#![deny(unsafe_op_in_unsafe_fn)]

mod dma;
mod hc;
mod sync;
mod usb;

use core::ffi::c_void;
use core::sync::atomic::{AtomicBool, AtomicU32, Ordering};

use myos_abi::{
    ABI_VERSION, ApiCell, KernelApi, MYOS_IRQ_INTX, USB_EGONE, USB_HOST_VERSION, USB_LABEL_MAX,
    USB_SERVICE,
    UsbCompletion, UsbDeviceInfo, UsbDriverOps, UsbHostOps, status_fail, status_ok,
};

static API: ApiCell = ApiCell::new();
/// The controllers, each set once by `probe` and read by every context
/// after (`controller`).
static CONTROLLERS: [sync::Once<hc::Controller>; hc::MAX_CTRL] = [const { sync::Once::new() }; hc::MAX_CTRL];
/// The USB thread sleeps on this key; the event handler, `driver_register`
/// and the hub calls wake it.
pub static THREAD_KEY: AtomicU32 = AtomicU32::new(0);
/// A driver registered: offer the unclaimed interfaces again.
static REOFFER: AtomicBool = AtomicBool::new(false);
static PROC_DIRTY: AtomicBool = AtomicBool::new(false);

pub fn api() -> &'static KernelApi {
    API.get()
}

pub fn controller(i: u8) -> Option<&'static hc::Controller> {
    CONTROLLERS.get(usize::from(i))?.get()
}

/// Sleep the calling task `ms` milliseconds.
pub fn sleep_ms(ms: u64) {
    let until = api().monotonic_ns() + ms * 1_000_000;
    api().task_sleep_until(until);
}

fn wake_thread() {
    api().wake(THREAD_KEY.as_ptr() as usize);
}

/// `/proc/usb` is regenerated by the thread after a change.
pub fn proc_update() {
    PROC_DIRTY.store(true, Ordering::Release);
    wake_thread();
}

fn proc_write() {
    let mut buf = [0u8; 4096];
    let n = usb::proc_text(&mut buf);
    api().proc_register("usb", &buf[..n]);
}

/// A small text writer for the proc node.
pub struct Writer<'a> {
    pub buf: &'a mut [u8],
    pub len: usize,
}

impl Writer<'_> {
    pub fn bytes(&mut self, b: &[u8]) {
        let n = b.len().min(self.buf.len() - self.len);
        self.buf[self.len..self.len + n].copy_from_slice(&b[..n]);
        self.len += n;
    }
    pub fn str(&mut self, s: &str) {
        self.bytes(s.as_bytes());
    }
    pub fn dec(&mut self, mut v: u32) {
        let mut t = [0u8; 10];
        let mut n = 0;
        loop {
            t[n] = b'0' + (v % 10) as u8;
            n += 1;
            v /= 10;
            if v == 0 {
                break;
            }
        }
        t[..n].reverse();
        self.bytes(&t[..n]);
    }
    fn hexn(&mut self, v: u64, digits: usize) {
        let mut t = [0u8; 16];
        for i in 0..digits {
            let d = ((v >> (4 * (digits - 1 - i))) & 0xF) as u8;
            t[i] = if d < 10 { b'0' + d } else { b'a' + d - 10 };
        }
        self.bytes(&t[..digits]);
    }
    pub fn hex(&mut self, v: u32) {
        self.str("0x");
        self.hexn(u64::from(v), 3);
    }
    pub fn hex4(&mut self, v: u16) {
        self.hexn(u64::from(v), 4);
    }
    pub fn hex2(&mut self, v: u8) {
        self.hexn(u64::from(v), 2);
    }
}

// ---- The service table ------------------------------------------------------

static HOST_OPS: UsbHostOps = UsbHostOps {
    version: USB_HOST_VERSION,
    driver_register,
    control,
    bulk,
    interrupt_start,
    clear_halt,
    hub_configure,
    hub_attach,
    hub_detach,
    device_info,
    interface_label,
};

unsafe extern "C" fn driver_register(ops: *const UsbDriverOps) -> i32 {
    if ops.is_null() {
        return -1;
    }
    let mut drivers = usb::DRIVERS.lock();
    let Some(slot) = drivers.iter().position(|d| d.is_none()) else {
        return -1;
    };
    // SAFETY: a driver's table lives as long as its module, which stays
    // loaded while it is registered here (`docs/usb.md`).
    drivers[slot] = Some(unsafe { &*ops });
    drop(drivers);
    REOFFER.store(true, Ordering::Release);
    wake_thread();
    0
}

/// `usb::with_device` for a hook: the device's lock held for `f`, and
/// `USB_EGONE` when the device is not there.
fn on_device(dev: u32, f: impl FnOnce(&hc::Controller, &usb::Slot, &mut usb::Device) -> i32) -> i32 {
    usb::with_device(dev, f).unwrap_or_else(|e| e)
}

unsafe extern "C" fn control(dev: u32, request_type: u8, request: u8, value: u16, index: u16, data: *mut u8, len: u16) -> i32 {
    if len != 0 && data.is_null() {
        return -1;
    }
    on_device(dev, |c, s, d| usb::control(c, s, d, request_type, request, value, index, data, len))
}

unsafe extern "C" fn bulk(dev: u32, endpoint: u8, data: *mut u8, len: usize, timeout_ms: u32) -> i32 {
    if data.is_null() && len != 0 {
        return -1;
    }
    on_device(dev, |c, s, d| usb::bulk(c, s, d, endpoint, data, len, timeout_ms))
}

unsafe extern "C" fn interrupt_start(dev: u32, endpoint: u8, data: *mut u8, len: usize, done: UsbCompletion, ctx: *mut c_void) -> i32 {
    if data.is_null() || len == 0 {
        return -1;
    }
    on_device(dev, |c, s, d| usb::interrupt_start(c, s, d, endpoint, data, len, done, ctx))
}

unsafe extern "C" fn clear_halt(dev: u32, endpoint: u8) -> i32 {
    on_device(dev, |c, s, d| usb::clear_halt(c, s, d, endpoint))
}

unsafe extern "C" fn hub_configure(dev: u32, ports: u8, tt_think: u8, multi_tt: u8) -> i32 {
    on_device(dev, |c, _, d| usb::hub_configure(c, d, ports, tt_think, multi_tt != 0))
}

/// The controller of the hub `dev`, if the hub is there.
fn hub_controller(dev: u32) -> Option<&'static hc::Controller> {
    let index = usb::with_device(dev, |c, _, _| c.index).ok()?;
    controller(index)
}

unsafe extern "C" fn hub_attach(dev: u32, port: u8, speed: u8) -> i32 {
    let Some(c) = hub_controller(dev) else {
        return USB_EGONE;
    };
    if let Some(child) = usb::find(c.index, dev, port) {
        usb::detach_id(c, child);
    }
    match usb::attach(c, Some((dev, port)), 0, speed) {
        Ok(id) => id as i32,
        Err(e) => {
            enumeration_failed(e);
            e
        }
    }
}

unsafe extern "C" fn hub_detach(dev: u32, port: u8) {
    let Some(c) = hub_controller(dev) else {
        return;
    };
    if let Some(child) = usb::find(c.index, dev, port) {
        usb::detach_id(c, child);
    }
}

unsafe extern "C" fn device_info(dev: u32, info: *mut UsbDeviceInfo) -> i32 {
    if info.is_null() {
        return -1;
    }
    on_device(dev, |_, _, d| {
        unsafe {
            *info = d.info;
        }
        0
    })
}

unsafe extern "C" fn interface_label(dev: u32, intf: u8, label: *const u8, len: usize) -> i32 {
    let len = len.min(USB_LABEL_MAX);
    if len != 0 && label.is_null() {
        return -1;
    }
    let rc = on_device(dev, |_, _, d| {
        let Some(i) = d.interfaces.iter_mut().flatten().find(|i| i.info.number == intf) else {
            return -1;
        };
        if len != 0 {
            i.label[..len].copy_from_slice(unsafe { core::slice::from_raw_parts(label, len) });
        }
        i.label_len = len as u8;
        0
    });
    if rc == 0 {
        proc_update();
    }
    rc
}

// ---- Interrupts and the thread -----------------------------------------------

static IRQS: AtomicU32 = AtomicU32::new(0);

pub fn irqs() -> u32 {
    IRQS.load(Ordering::Relaxed)
}

unsafe extern "C" fn irq_handler(ctx: *mut c_void) {
    IRQS.fetch_add(1, Ordering::Relaxed);
    let Some(c) = controller(ctx as usize as u8) else {
        return;
    };
    hc::process_events(c);
}

/// A root port's status changed (or the initial scan): a new device is
/// reset and enumerated, a vanished one detached.
fn root_port(c: &hc::Controller, port: usize) {
    let s = hc::port_status(c, port);
    hc::port_ack(c, port);
    let present = usb::find(c.index, 0, port as u8 + 1);
    if s.connected && present.is_none() {
        // Debounce, then reset (USB 2) or just take the enabled link (USB 3).
        sleep_ms(100);
        let s = hc::port_status(c, port);
        if !s.connected {
            return;
        }
        let enabled = if s.enabled && c.port_major[port.min(63)] == 3 {
            true
        } else {
            hc::port_reset(c, port)
        };
        if !enabled {
            return;
        }
        let s = hc::port_status(c, port);
        let speed = usb::speed_from_psi(s.speed);
        if let Err(e) = usb::attach(c, None, port as u8 + 1, speed) {
            enumeration_failed(e);
        }
    } else if !s.connected {
        if let Some(id) = present {
            usb::detach_id(c, id);
        }
    }
}

/// `[ FAIL ] usb: <step> failed (<code>)`: the step of `usb::enumerate`
/// and the `USB_E*` or command error.
pub fn enumeration_failed(e: i32) {
    let mut buf = [0u8; 96];
    let mut w = Writer { buf: &mut buf, len: 0 };
    w.str("usb: ");
    w.str(*usb::STEP.lock());
    w.str(" failed (");
    if e < 0 {
        w.str("-");
    }
    w.dec(e.unsigned_abs());
    w.str(") irqs ");
    w.dec(IRQS.load(Ordering::Relaxed));
    w.str(" events ");
    w.dec(controller(0).map_or(0, |c| c.events.load(Ordering::Relaxed)));
    let n = w.len;
    status_fail(api(), core::str::from_utf8(&buf[..n]).unwrap_or("usb"));
}

unsafe extern "C" fn thread_main(_ctx: *mut c_void) {
    // The initial scan: every root port with a device.
    for i in 0..hc::MAX_CTRL as u8 {
        if let Some(c) = controller(i) {
            for port in 0..usize::from(c.ports) {
                if hc::port_status(c, port).connected {
                    c.port_change.fetch_or(1 << port.min(63), Ordering::Relaxed);
                }
            }
        }
    }
    loop {
        let seq = api().wait_seq();
        let mut worked = false;
        for i in 0..hc::MAX_CTRL as u8 {
            let Some(c) = controller(i) else {
                continue;
            };
            if !c.irq_on.load(Ordering::Relaxed) {
                hc::process_events(c);
            }
            let changed = c.port_change.swap(0, Ordering::AcqRel);
            if changed != 0 {
                worked = true;
                for port in 0..usize::from(c.ports).min(64) {
                    if changed & (1 << port) != 0 {
                        root_port(c, port);
                    }
                }
            }
            if c.async_done.swap(false, Ordering::AcqRel) {
                worked = true;
                usb::run_async_completions(c);
            }
            if REOFFER.swap(false, Ordering::AcqRel) {
                worked = true;
                usb::offer_all(c);
            }
        }
        if PROC_DIRTY.swap(false, Ordering::AcqRel) {
            proc_write();
        }
        if worked {
            continue;
        }
        // Without an interrupt the ring is polled every 20 ms.
        let polled = (0..hc::MAX_CTRL as u8).any(|i| controller(i).is_some_and(|c| !c.irq_on.load(Ordering::Relaxed)));
        let now = api().monotonic_ns();
        let deadline = if polled { now + 20_000_000 } else { now + 1_000_000_000 };
        api().block_until(THREAD_KEY.as_ptr() as usize, seq, deadline);
    }
}

// ---- Probing ---------------------------------------------------------------

const CLASS_SERIAL_BUS: u8 = 0x0C;
const SUBCLASS_USB: u8 = 0x03;
const PROGIF_XHCI: u8 = 0x30;

/// Every xHCI controller on the bus not attached yet: the number brought up.
fn probe(api: &KernelApi) -> usize {
    let mut new = 0;
    let mut nth = 0u32;
    loop {
        let (mut bus, mut slot, mut func) = (0u8, 0u8, 0u8);
        if api.pci_find_class(CLASS_SERIAL_BUS, SUBCLASS_USB, nth, &mut bus, &mut slot, &mut func) != 0 {
            break;
        }
        nth += 1;
        let class = api.pci_cfg_read32(bus, slot, func, 0x08);
        if ((class >> 8) & 0xFF) as u8 != PROGIF_XHCI {
            continue;
        }
        let Some(index) = CONTROLLERS.iter().position(|c| c.get().is_none()) else {
            break;
        };
        api.pci_enable(bus, slot, func);
        let (mut va, mut size) = (0usize, 0u64);
        if api.pci_bar_map(bus, slot, func, 0, &mut va, &mut size) != 0 || size < 0x1000 {
            continue;
        }
        if CONTROLLERS.iter().filter_map(sync::Once::get).any(|c| c.mmio() == va) {
            continue;
        }
        match hc::init(va, index as u8) {
            Ok(c) => {
                // In the table before the interrupt is on: the controller
                // raises one as soon as it runs (the ports with devices),
                // and a handler finding no controller would leave IP set,
                // which blocks every later interrupt.
                CONTROLLERS[index].set(c);
                let mut msix = 0u16;
                let rc = api.pci_irq_enable(bus, slot, func, "xhci", irq_handler, index as *mut c_void, &mut msix);
                let _ = msix == MYOS_IRQ_INTX;
                if let Some(c) = controller(index as u8) {
                    c.irq_on.store(rc == 0, Ordering::Release);
                }
                new += 1;
            }
            Err(why) => {
                let mut buf = [0u8; 64];
                let mut w = Writer { buf: &mut buf, len: 0 };
                w.str("xhci: ");
                w.str(why);
                let n = w.len;
                status_fail(api, core::str::from_utf8(&buf[..n]).unwrap_or("xhci"));
            }
        }
    }
    new
}

#[inline(never)]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn module_init(api_ptr: *const KernelApi) -> i32 {
    if api_ptr.is_null() {
        return -1;
    }
    let api: &'static KernelApi = unsafe { &*api_ptr };
    if api.abi_version != ABI_VERSION {
        return -2;
    }
    unsafe { API.set(api) };
    if probe(api) == 0 {
        api.write_str("xhci none\n");
        return 0;
    }
    if api.service_register(USB_SERVICE, &HOST_OPS) != 0 {
        status_fail(api, "xhci: usb service");
        return -3;
    }
    if api.thread_spawn("usb", thread_main, core::ptr::null_mut()) != 0 {
        status_fail(api, "xhci: no thread");
        return -4;
    }
    proc_write();
    let mut buf = [0u8; 64];
    let mut w = Writer { buf: &mut buf, len: 0 };
    w.str("xhci: ");
    for i in 0..hc::MAX_CTRL as u8 {
        if let Some(c) = controller(i) {
            if i > 0 {
                w.str(", ");
            }
            w.dec(u32::from(c.ports));
            w.str(" ports");
            w.str(if c.irq_on.load(Ordering::Relaxed) { " irq" } else { " polled" });
        }
    }
    let n = w.len;
    status_ok(api, core::str::from_utf8(&buf[..n]).unwrap_or("xhci"));
    0
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn module_exit() {}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn module_rescan() {
    // A controller that appeared after boot: bring it up; its ports are
    // scanned by the thread like any other.
    if probe(api()) > 0 {
        for i in 0..hc::MAX_CTRL as u8 {
            if let Some(c) = controller(i) {
                for port in 0..usize::from(c.ports) {
                    if hc::port_status(c, port).connected {
                        c.port_change.fetch_or(1 << port.min(63), Ordering::Relaxed);
                    }
                }
            }
        }
        wake_thread();
    }
}

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    let api = api();
    status_fail(api, "xhci: panic");
    loop {
        api.task_yield();
    }
}
