#!/usr/bin/env bash
# Prepare the dropbear source tree for myos builds.
# Extracts the verified tarball into target/dropbear-myos-build and installs
# myos overlays (config.h, localoptions.h). Upstream sources stay patch-free.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=versions.env
source "$HERE/versions.env"

TARBALL="$ROOT/target/dropbear-${MYOS_DROPBEAR_VERSION}.tar.bz2"
WORK="$ROOT/target/dropbear-myos-build"

[[ -f "$TARBALL" ]] || "$HERE/fetch.sh"

if [[ ! -d "$WORK/src" ]]; then
  rm -rf "$WORK"
  mkdir -p "$WORK"
  # CI image may lack bzip2(1); prefer it, else decompress via python3.
  if command -v bzip2 >/dev/null 2>&1 || command -v lbzip2 >/dev/null 2>&1; then
    tar -xjf "$TARBALL" -C "$WORK" --strip-components=1
  else
    python3 - "$TARBALL" "$WORK" <<'PY'
import bz2, sys, tarfile
from pathlib import Path
tarball, dest = sys.argv[1], Path(sys.argv[2])
with bz2.open(tarball, "rb") as raw, tarfile.open(fileobj=raw, mode="r|") as tf:
    # strip the single top-level directory dropbear-VERSION/
    for m in tf:
        parts = Path(m.name).parts
        if len(parts) <= 1:
            continue
        m.name = str(Path(*parts[1:]))
        try:
            tf.extract(m, path=dest, filter="data")
        except TypeError:
            tf.extract(m, path=dest)
PY
  fi
fi

# myos overlays win (copied after extraction; idempotent on re-runs).
cp "$HERE/config-myos.h" "$WORK/src/config.h"
cp "$HERE/localoptions.h" "$WORK/src/localoptions.h"
cp "$HERE/myos_compat.h" "$WORK/src/myos_compat.h"

# Generate default_options_guard.h exactly like the upstream Makefile rule
# (ifndef_wrapper.sh wraps every #define in #ifndef/#endif so localoptions
# and -D flags can override).
{
  printf '/*\n > > > Do not edit this file (default_options_guard.h) < < <\nGenerated from'
  printf ' default_options.h\nLocal customisation goes in localoptions.h\n*/\n\n'
  sh "$WORK/src/ifndef_wrapper.sh" < "$WORK/src/default_options.h"
} > "$WORK/src/default_options_guard.h"

echo "dropbear prepared in $WORK"
