[workspace]

[package]
name = "init"
version = "0.1.0"
edition = "2024"
publish = false
description = "Userspace PID1: smoke fork/`/ok`, then respawn getty → login → /sh."

[[bin]]
name = "init"
test = false
bench = false

[dependencies]
myos-user = { path = "../lib" }

[profile.dev]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"

[profile.release]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"
