[workspace]

[package]
name = "netd"
version = "0.1.0"
edition = "2024"
publish = false
description = "Userspace netd: smoltcp over /dev/net0, Plan 9 /net via /dev/netd."

[[bin]]
name = "netd"
test = false
bench = false

[dependencies]
myos-user = { path = "../lib" }
myos-net = { path = "../net" }

[profile.dev]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"

[profile.release]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"
