[workspace]

[package]
name = "netfs"
version = "0.1.0"
edition = "2024"
publish = false
description = "Plan 9 /net kernel module: vfs_mount at /net plus /dev/netd channel to netd."

[[bin]]
name = "netfs"
test = false
bench = false

[dependencies]
myos-abi = { path = "../abi" }

[profile.dev]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"

[profile.release]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"
