[workspace]

[package]
name = "http"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"
description = "curl-like HTTP/HTTPS GET via Plan 9 /net/tcp + user/tls (mbedtls)."

[[bin]]
name = "http"
test = false
bench = false

[dependencies]
myos-user = { path = "../lib" }
myos-tls = { path = "../tls" }

[profile.dev]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"

[profile.release]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"
