[workspace]

[package]
name = "hello"
version = "0.1.0"
edition = "2024"
publish = false
description = "Sample loadable module: prints `mod ok` through KernelApi."

[[bin]]
name = "hello"
test = false
bench = false

[dependencies]
myos-abi = { path = "../abi" }

[profile.dev]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"

[profile.release]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"
