[workspace]

[package]
name = "myos-user"
version = "0.1.0"
edition = "2024"
publish = false
description = "Userspace syscall wrappers for myos."

[lib]
name = "myos_user"
path = "src/lib.rs"

[profile.dev]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"

[profile.release]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"
