[workspace]

[package]
name = "acpi"
version = "0.1.0"
edition = "2024"
publish = false
description = "Minimal ACPI table parse + AML interpreter; publishes /proc/acpi/*."

[[bin]]
name = "acpi"
test = false
bench = false

[dependencies]
myos-abi = { path = "../abi" }

[profile.dev]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"

[profile.release]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"
