#!/usr/bin/env bash
# Shared myos std/sysroot paths and version stamp for cache invalidation.
set -euo pipefail

MYOS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export MYOS_ROOT

myos_read_toolchain_channel() {
  local file="$MYOS_ROOT/rust-toolchain.toml"
  if [[ ! -f "$file" ]]; then
    echo "nightly-2026-07-26"
    return
  fi
  sed -n 's/^channel = "\(.*\)"/\1/p' "$file" | head -1
}

export MYOS_NIGHTLY="${MYOS_NIGHTLY:-$(myos_read_toolchain_channel)}"
export MYOS_SYSROOT="${MYOS_SYSROOT:-$MYOS_ROOT/target/myos-sysroot}"
export MYOS_SYSROOT_VERSION="$MYOS_SYSROOT/.myos-sysroot-version"
export MYOS_SYSROOT_MANIFEST="$MYOS_SYSROOT/myos-manifest.toml"

MYOS_USER_TRIPLES=(
  x86_64-unknown-myos
  aarch64-unknown-myos
  riscv64-unknown-myos
)

myos_sysroot_version_hash() {
  local h
  h="$(
    {
      echo "toolchain=$MYOS_NIGHTLY"
      sha256sum "$MYOS_ROOT/std/patches/wire-myos.py"
      find "$MYOS_ROOT/std/pal" "$MYOS_ROOT/std/sys" "$MYOS_ROOT/std/os" \
        "$MYOS_ROOT/targets" -type f -print0 2>/dev/null \
        | sort -z | xargs -0 sha256sum
    } | sha256sum | awk '{print $1}'
  )"
  printf '%s' "$h"
}

myos_sysroot_is_current() {
  [[ -f "$MYOS_SYSROOT_VERSION" ]] \
    && [[ -f "$MYOS_SYSROOT_MANIFEST" ]] \
    && [[ "$(cat "$MYOS_SYSROOT_VERSION")" == "$(myos_sysroot_version_hash)" ]] \
    && [[ -d "$MYOS_SYSROOT/lib/rustlib/x86_64-unknown-myos/lib" ]] \
    && [[ -d "$MYOS_SYSROOT/lib/rustlib/aarch64-unknown-myos/lib" ]] \
    && [[ -d "$MYOS_SYSROOT/lib/rustlib/riscv64-unknown-myos/lib" ]]
}

myos_install_target_spec() {
  local triple="$1"
  cp "$MYOS_ROOT/targets/${triple}.json" \
    "$MYOS_SYSROOT/lib/rustlib/${triple}.json"
}

myos_install_std_rlibs() {
  local triple="$1"
  local deps_dir="$2"
  local dest="$MYOS_SYSROOT/lib/rustlib/${triple}/lib"
  mkdir -p "$dest"
  shopt -s nullglob
  local artifacts=( "$deps_dir"/*.rlib "$deps_dir"/*.rmeta )
  shopt -u nullglob
  if ((${#artifacts[@]} == 0)); then
    echo "error: no std rlibs in $deps_dir" >&2
    exit 1
  fi
  cp -a "${artifacts[@]}" "$dest/"
  myos_install_target_spec "$triple"
}

myos_write_sysroot_manifest() {
  local version="$1"
  cat >"$MYOS_SYSROOT_MANIFEST" <<EOF
# myos prebuilt sysroot — generated by scripts/build-sysroot.sh
channel = "$MYOS_NIGHTLY"
version = "$version"
triples = ["x86_64-unknown-myos", "aarch64-unknown-myos", "riscv64-unknown-myos"]
repository = "https://github.com/davide-matasci/myos"
pal_hash = "$version"
EOF
}

myos_export_toolchain_env() {
  export RUSTC_BOOTSTRAP=1
  export MYOS_SYSROOT
  export RUSTC="$MYOS_ROOT/scripts/myos-rustc.sh"
}

myos_cargo_build_std() {
  local triple="$1"
  local profile="${2:-release}"
  local target_json="$MYOS_ROOT/targets/${triple}.json"
  local target_dir="$MYOS_ROOT/target/sysroot-build-${triple}"
  local manifest="$MYOS_ROOT/std/examples/hello/Cargo.toml"
  local -a profile_args=()
  if [[ "$profile" == release ]]; then
    profile_args=(--release)
  fi

  myos_export_toolchain_env
  cargo "+$MYOS_NIGHTLY" build \
    -Z build-std=std,panic_abort \
    -Z build-std-features=compiler-builtins-mem \
    -Z unstable-options \
    -Z json-target-spec \
    --target "$target_json" \
    --target-dir "$target_dir" \
    "${profile_args[@]}" \
    --manifest-path "$manifest"

  myos_install_std_rlibs "$triple" "$target_dir/${triple}/${profile}/deps"
}

myos_cargo_build_app() {
  local triple="$1"
  local profile="${2:-release}"
  local target_dir="$3"
  local manifest="$4"
  local bin="$5"
  local target_json="$MYOS_ROOT/targets/${triple}.json"
  local -a profile_args=()
  if [[ "$profile" == release ]]; then
    profile_args=(--release)
  fi

  myos_export_toolchain_env
  cargo "+$MYOS_NIGHTLY" build \
    -Z unstable-options \
    -Z json-target-spec \
    --target "$target_json" \
    --target-dir "$target_dir" \
    "${profile_args[@]}" \
    --manifest-path "$manifest" \
    --bin "$bin"
}

MYOS_STD_HELLO_VERSION="$MYOS_ROOT/target/.myos-std-hello-version"

myos_std_hello_version_hash() {
  local h
  h="$(
    {
      myos_sysroot_version_hash
      sha256sum "$MYOS_ROOT/scripts/build-std-hello.sh"
      find "$MYOS_ROOT/std/examples" -type f -print0 2>/dev/null \
        | sort -z | xargs -0 sha256sum
    } | sha256sum | awk '{print $1}'
  )"
  printf '%s' "$h"
}

myos_std_hello_is_current() {
  local triple name
  [[ -f "$MYOS_STD_HELLO_VERSION" ]] \
    && [[ "$(cat "$MYOS_STD_HELLO_VERSION")" == "$(myos_std_hello_version_hash)" ]] \
    || return 1
  for triple in "${MYOS_USER_TRIPLES[@]}"; do
    for name in hello cat echo bigalloc; do
      [[ -f "$MYOS_ROOT/target/std-${name}-${triple}" ]] || return 1
    done
  done
}
