[workspace]

[package]
name = "heap"
version = "0.1.0"
edition = "2024"
publish = false
description = "CI-only heavy smoke (std/C/sbase/uutils/bigalloc); typed at $ by wait_ci."

[[bin]]
name = "heap"
test = false
bench = false

[dependencies]
myos-user = { path = "../lib" }

[profile.dev]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"

[profile.release]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"
