[workspace]

[package]
name = "mount"
version = "0.1.0"
edition = "2024"
publish = false
description = "Userspace mount(2): mount /dev/vda /mnt fat"

[[bin]]
name = "mount"
test = false
bench = false

[dependencies]
myos-user = { path = "../lib" }

[profile.dev]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"

[profile.release]
panic = "abort"
opt-level = "s"
debug = false
strip = "debuginfo"
