name: dispatch-test
on:
  workflow_dispatch:
    inputs:
      build_iso:
        description: test bool
        type: boolean
        default: false
permissions:
  contents: read

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: echo "A ran"
  b-plain:
    needs: a
    runs-on: ubuntu-latest
    if: needs.a.result == 'success' && github.event_name == 'workflow_dispatch'
    steps:
      - run: echo "B-plain ran"
  b-container:
    needs: a
    runs-on: ubuntu-latest
    container: ghcr.io/davide-matasci/myos-ci:latest
    if: needs.a.result == 'success' && github.event_name == 'workflow_dispatch'
    steps:
      - run: echo "B-container ran"
  b-inputs:
    needs: a
    runs-on: ubuntu-latest
    if: needs.a.result == 'success' && inputs.build_iso == true
    steps:
      - run: echo "B-inputs ran"
