// Auto-generated by ports/crates/libc/generate-libc-rustix-stubs.py — compile-time rustix groundwork.
// Runtime ENOSYS is fine until individual syscalls matter.

pub type in_addr_t = u32;
pub type in_port_t = u16;
pub type rlim_t = u64;
pub type idtype_t = c_uint;
pub type __rlimit_resource_t = c_uint;

s! {
    pub struct msghdr {
        pub msg_name: *mut c_void,
        pub msg_namelen: socklen_t,
        pub msg_iov: *mut iovec,
        pub msg_iovlen: c_int,
        pub msg_control: *mut c_void,
        pub msg_controllen: size_t,
        pub msg_flags: c_int,
    }

    pub struct cmsghdr {
        pub cmsg_len: size_t,
        pub cmsg_level: c_int,
        pub cmsg_type: c_int,
    }

    pub struct siginfo_t {
        pub si_signo: c_int,
        pub si_errno: c_int,
        pub si_code: c_int,
        pub _pad: [c_int; 29],
    }

    pub struct flock {
        pub l_type: c_short,
        pub l_whence: c_short,
        pub l_start: off_t,
        pub l_len: off_t,
        pub l_pid: pid_t,
    }

    pub struct rlimit {
        pub rlim_cur: rlim_t,
        pub rlim_max: rlim_t,
    }

    pub struct fsid_t {
        __val: [c_int; 2],
    }

    pub struct in_addr {
        pub s_addr: in_addr_t,
    }

    pub struct in6_addr {
        pub s6_addr: [u8; 16],
    }

    pub struct sockaddr {
        pub sa_family: sa_family_t,
        pub sa_data: [c_char; 14],
    }

    pub struct sockaddr_in {
        pub sin_family: sa_family_t,
        pub sin_port: in_port_t,
        pub sin_addr: in_addr,
        pub sin_zero: [u8; 8],
    }

    pub struct sockaddr_in6 {
        pub sin6_family: sa_family_t,
        pub sin6_port: in_port_t,
        pub sin6_flowinfo: u32,
        pub sin6_addr: in6_addr,
        pub sin6_scope_id: u32,
    }

    pub struct sockaddr_storage {
        pub ss_family: sa_family_t,
        pub __data: [u8; 126],
    }

    pub struct linger {
        pub l_onoff: c_int,
        pub l_linger: c_int,
    }

    pub struct ip_mreq {
        pub imr_multiaddr: in_addr,
        pub imr_interface: in_addr,
    }

    pub struct ipv6_mreq {
        pub ipv6mr_multiaddr: in6_addr,
        pub ipv6mr_interface: c_uint,
    }

    pub struct statfs {
        pub f_type: c_long,
        pub f_bsize: c_long,
        pub f_blocks: u64,
        pub f_bfree: u64,
        pub f_bavail: u64,
        pub f_files: u64,
        pub f_ffree: u64,
        pub f_fsid: fsid_t,
        pub f_namelen: c_long,
        pub f_frsize: c_long,
        pub f_spare: [c_long; 5],
    }

    pub struct statvfs {
        pub f_bsize: c_ulong,
        pub f_frsize: c_ulong,
        pub f_blocks: u64,
        pub f_bfree: u64,
        pub f_bavail: u64,
        pub f_files: u64,
        pub f_ffree: u64,
        pub f_favail: u64,
        pub f_fsid: c_ulong,
        pub f_flag: c_ulong,
        pub f_namemax: c_ulong,
        pub f_spare: [c_int; 6],
    }

    pub struct sockaddr_un {
        pub sun_family: sa_family_t,
        pub sun_path: [c_char; 108],
    }
}

impl siginfo_t {
    pub unsafe fn si_status(&self) -> c_int {
        0
    }
}

const fn cmsg_align(len: usize) -> usize {
    (len + core::mem::size_of::<usize>() - 1) & !(core::mem::size_of::<usize>() - 1)
}

f! {
    pub unsafe fn CMSG_FIRSTHDR(mhdr: *const msghdr) -> *mut cmsghdr {
        if (*mhdr).msg_controllen >= core::mem::size_of::<cmsghdr>() {
            (*mhdr).msg_control.cast()
        } else {
            core::ptr::null_mut()
        }
    }

    pub unsafe fn CMSG_DATA(cmsg: *const cmsghdr) -> *mut c_uchar {
        (cmsg as *mut cmsghdr).offset(1).cast()
    }

    pub const unsafe fn CMSG_SPACE(length: c_uint) -> c_uint {
        (cmsg_align(length as usize) + cmsg_align(core::mem::size_of::<cmsghdr>())) as c_uint
    }

    pub const unsafe fn CMSG_LEN(length: c_uint) -> c_uint {
        cmsg_align(core::mem::size_of::<cmsghdr>()) as c_uint + length
    }

    pub unsafe fn CMSG_NXTHDR(mhdr: *const msghdr, cmsg: *const cmsghdr) -> *mut cmsghdr {
        let end = unsafe { (*mhdr).msg_control.cast::<u8>().add((*mhdr).msg_controllen) };
        let next = unsafe {
            cmsg.cast::<u8>()
                .add(cmsg_align((*cmsg).cmsg_len as usize))
                .cast::<cmsghdr>()
        };
        if next.cast::<u8>() >= end {
            core::ptr::null_mut()
        } else {
            next as *mut cmsghdr
        }
    }
}

// RTLD_DEFAULT lives in linux_l4re_shared in upstream libc; omit duplicate if present.
#[allow(unused)]
const _RTLD_DEFAULT_PLACEHOLDER: () = ();

// Linux-compatible constants (from upstream libc where available).
pub const AF_APPLETALK: c_int = 16;
pub const AF_ASH: c_int = 18;
pub const AF_ATMPVC: c_int = 8;
pub const AF_ATMSVC: c_int = 20;
pub const AF_AX25: c_int = 3;
pub const AF_BLUETOOTH: c_int = 10;
pub const AF_BRIDGE: c_int = 7;
pub const AF_CAN: c_int = 29;
pub const AF_DECnet: c_int = 12;
pub const AF_ECONET: c_int = 19;
pub const AF_IEEE802154: c_int = 36;
pub const AF_INET: c_int = 2;
pub const AF_INET6: c_int = 26;
pub const AF_IPX: c_int = 23;
pub const AF_IRDA: c_int = 23;
pub const AF_ISDN: c_int = 26;
pub const AF_IUCV: c_int = 32;
pub const AF_KEY: c_int = 15;
pub const AF_LLC: c_int = 26;
pub const AF_NETBEUI: c_int = 13;
pub const AF_NETLINK: c_int = 16;
pub const AF_NETROM: c_int = 6;
pub const AF_PACKET: c_int = 17;
pub const AF_PHONET: c_int = 35;
pub const AF_PPPOX: c_int = 24;
pub const AF_RDS: c_int = 21;
pub const AF_ROSE: c_int = 11;
pub const AF_RXRPC: c_int = 33;
pub const AF_SECURITY: c_int = 14;
pub const AF_SNA: c_int = 11;
pub const AF_TIPC: c_int = 30;
pub const AF_UNSPEC: c_int = 0;
pub const AF_WANPIPE: c_int = 25;
pub const AF_X25: c_int = 9;
pub const AT_EACCESS: c_int = 0x0001;
pub const AT_REMOVEDIR: c_int = 0x0008;
pub const AT_SYMLINK_FOLLOW: c_int = 0x0004;
pub const AT_SYMLINK_NOFOLLOW: c_int = 0x0002;
pub const CLD_CONTINUED: c_int = 6;
pub const CLD_DUMPED: c_int = 3;
pub const CLD_EXITED: c_int = 1;
pub const CLD_KILLED: c_int = 2;
pub const CLD_STOPPED: c_int = 5;
pub const CLD_TRAPPED: c_int = 4;
pub const CLOCK_PROCESS_CPUTIME_ID: crate::clockid_t = 3;
pub const CLOCK_THREAD_CPUTIME_ID: crate::clockid_t = 4;
pub const DT_BLK: u8 = 6;
pub const E2BIG: c_int = 7;
pub const EADDRINUSE: c_int = 248;
pub const EADDRNOTAVAIL: c_int = 249;
pub const EADV: c_int = 68;
pub const EAFNOSUPPORT: c_int = 247;
pub const EAGAIN: c_int = 11;
pub const EALREADY: c_int = 237;
pub const EBADE: c_int = 50;
pub const EBADFD: c_int = 81;
pub const EBADMSG: c_int = 77;
pub const EBADR: c_int = 51;
pub const EBADRQC: c_int = 54;
pub const EBADSLT: c_int = 55;
pub const EBFONT: c_int = 57;
pub const EBUSY: c_int = 16;
pub const ECANCELED: c_int = 47;
pub const ECHRNG: c_int = 37;
pub const ECOMM: c_int = 70;
pub const ECONNABORTED: c_int = 253;
pub const ECONNREFUSED: c_int = 261;
pub const ECONNRESET: c_int = 254;
pub const EDEADLK: c_int = 45;
pub const EDEADLOCK: c_int = 56;
pub const EDESTADDRREQ: c_int = 239;
pub const EDOM: c_int = 33;
pub const EDOTDOT: i32 = 73;
pub const EDQUOT: c_int = 49;
pub const EFBIG: c_int = 27;
pub const EHOSTDOWN: c_int = 264;
pub const EHOSTUNREACH: c_int = 265;
pub const EHWPOISON: i32 = 133;
pub const EIDRM: c_int = 36;
pub const EILSEQ: c_int = 88;
pub const EINPROGRESS: c_int = 236;
pub const EISCONN: c_int = 256;
pub const EISDIR: c_int = 21;
pub const EISNAM: i32 = 120;
pub const EKEYEXPIRED: i32 = 127;
pub const EKEYREJECTED: i32 = 129;
pub const EKEYREVOKED: i32 = 128;
pub const EL2HLT: c_int = 44;
pub const EL2NSYNC: c_int = 38;
pub const EL3HLT: c_int = 39;
pub const EL3RST: c_int = 40;
pub const ELIBACC: c_int = 83;
pub const ELIBBAD: c_int = 84;
pub const ELIBEXEC: c_int = 87;
pub const ELIBMAX: c_int = 86;
pub const ELIBSCN: c_int = 85;
pub const ELNRNG: c_int = 41;
pub const EMEDIUMTYPE: i32 = 124;
pub const EMFILE: c_int = 24;
pub const EMLINK: c_int = 31;
pub const EMSGSIZE: c_int = 240;
pub const EMULTIHOP: c_int = 74;
pub const ENAVAIL: i32 = 119;
pub const ENETDOWN: c_int = 250;
pub const ENETRESET: c_int = 252;
pub const ENETUNREACH: c_int = 251;
pub const ENFILE: c_int = 23;
pub const ENOANO: c_int = 53;
pub const ENOBUFS: c_int = 255;
pub const ENOCSI: c_int = 43;
pub const ENODATA: c_int = 61;
pub const ENODEV: c_int = 19;
pub const ENOEXEC: c_int = 8;
pub const ENOKEY: i32 = 126;
pub const ENOLCK: c_int = 46;
pub const ENOLINK: c_int = 67;
pub const ENOMEDIUM: i32 = 123;
pub const ENOMSG: c_int = 35;
pub const ENONET: c_int = 64;
pub const ENOPKG: c_int = 65;
pub const ENOPROTOOPT: c_int = 242;
pub const ENOSPC: c_int = 28;
pub const ENOSR: c_int = 63;
pub const ENOSTR: c_int = 60;
pub const ENOTBLK: c_int = 15;
pub const ENOTCONN: c_int = 257;
pub const ENOTNAM: i32 = 118;
pub const ENOTRECOVERABLE: c_int = 95;
pub const ENOTSOCK: c_int = 238;
pub const ENOTSUP: c_int = 48;
pub const ENOTTY: c_int = 25;
pub const ENOTUNIQ: c_int = 80;
pub const ENXIO: c_int = 6;
pub const EOPNOTSUPP: c_int = 103;
pub const EOWNERDEAD: c_int = 58;
pub const EPFNOSUPPORT: c_int = 246;
pub const EPIPE: c_int = 32;
pub const EPROTO: c_int = 71;
pub const EPROTONOSUPPORT: c_int = 243;
pub const EPROTOTYPE: c_int = 241;
pub const ERANGE: c_int = 34;
pub const EREMCHG: c_int = 82;
pub const EREMOTE: c_int = 66;
pub const EREMOTEIO: i32 = 121;
pub const ERESTART: c_int = 91;
pub const ERFKILL: i32 = 132;
pub const EROFS: c_int = 30;
pub const ESHUTDOWN: c_int = 258;
pub const ESOCKTNOSUPPORT: c_int = 244;
pub const ESPIPE: c_int = 29;
pub const ESRCH: c_int = 3;
pub const ESRMNT: c_int = 69;
pub const ESTALE: c_int = 122;
pub const ESTRPIPE: c_int = 92;
pub const ETIME: c_int = 62;
pub const ETIMEDOUT: c_int = 260;
pub const ETOOMANYREFS: c_int = 259;
pub const ETXTBSY: c_int = 26;
pub const EUCLEAN: i32 = 117;
pub const EUNATCH: c_int = 42;
pub const EUSERS: c_int = 94;
pub const EWOULDBLOCK: c_int = EAGAIN;
pub const EXDEV: c_int = 18;
pub const EXFULL: c_int = 52;
pub const EXIT_FAILURE: c_int = 1;
pub const EXIT_SUCCESS: c_int = 0;
pub const FALLOC_FL_COLLAPSE_RANGE: c_int = 0x0008;
pub const FALLOC_FL_INSERT_RANGE: c_int = 0x0010;
pub const FALLOC_FL_KEEP_SIZE: c_int = 0x1000;
pub const FALLOC_FL_NO_HIDE_STALE: c_int = 0x04;
pub const FALLOC_FL_PUNCH_HOLE: c_int = 0x0001;
pub const FALLOC_FL_UNSHARE_RANGE: c_int = 0x0004;
pub const FALLOC_FL_ZERO_RANGE: c_int = 0x0002;
pub const FIONBIO: c_ulong = 0x8004667e;
pub const FIONREAD: c_ulong = 0x4004667f;
pub const F_DUPFD_CLOEXEC: c_int = 5;
pub const F_GETLK: c_int = 114;
pub const F_OK: c_int = 0;
pub const F_RDLCK: c_short = 1;
pub const F_SETLK: c_int = 106;
pub const F_SETLKW: c_int = 107;
pub const F_UNLCK: c_short = 2;
pub const F_WRLCK: c_short = 3;
pub const IPPROTO_AH: c_int = 51;
pub const IPPROTO_BEETPH: c_int = 94;
pub const IPPROTO_COMP: c_int = 108;
pub const IPPROTO_DCCP: c_int = 33;
pub const IPPROTO_EGP: c_int = 8;
pub const IPPROTO_ENCAP: c_int = 98;
pub const IPPROTO_ESP: c_int = 50;
pub const IPPROTO_FRAGMENT: c_int = 44;
pub const IPPROTO_GRE: c_int = 47;
pub const IPPROTO_ICMP: c_int = 1;
pub const IPPROTO_ICMPV6: c_int = 58;
pub const IPPROTO_IDP: c_int = 22;
pub const IPPROTO_IGMP: c_int = 2;
pub const IPPROTO_IP: c_int = 0;
pub const IPPROTO_IPIP: c_int = 4;
pub const IPPROTO_IPV6: c_int = 41;
pub const IPPROTO_MH: c_int = 135;
pub const IPPROTO_MPLS: c_int = 137;
pub const IPPROTO_MPTCP: c_int = 262;
pub const IPPROTO_MTP: c_int = 92;
pub const IPPROTO_PIM: c_int = 103;
pub const IPPROTO_PUP: c_int = 12;
pub const IPPROTO_RAW: c_int = 255;
pub const IPPROTO_ROUTING: c_int = 43;
pub const IPPROTO_RSVP: c_int = 46;
pub const IPPROTO_SCTP: c_int = 132;
pub const IPPROTO_TCP: c_int = 6;
pub const IPPROTO_TP: c_int = 29;
pub const IPPROTO_UDP: c_int = 17;
pub const IPPROTO_UDPLITE: c_int = 136;
pub const IPV6_ADD_MEMBERSHIP: c_int = 20;
pub const IPV6_DROP_MEMBERSHIP: c_int = 21;
pub const IPV6_MULTICAST_HOPS: c_int = 10;
pub const IPV6_MULTICAST_IF: c_int = 9;
pub const IPV6_MULTICAST_LOOP: c_int = 11;
pub const IPV6_TCLASS: c_int = 61;
pub const IPV6_UNICAST_HOPS: c_int = 4;
pub const IPV6_V6ONLY: c_int = 27;
pub const IP_ADD_MEMBERSHIP: c_int = 12;
pub const IP_DROP_MEMBERSHIP: c_int = 13;
pub const IP_MULTICAST_IF: c_int = 9;
pub const IP_MULTICAST_LOOP: c_int = 11;
pub const IP_MULTICAST_TTL: c_int = 10;
pub const IP_TTL: c_int = 4;
pub const LOCK_EX: c_int = 0x2;
pub const LOCK_NB: c_int = 0x4;
pub const LOCK_SH: c_int = 0x1;
pub const LOCK_UN: c_int = 0x8;
pub const MSG_CMSG_CLOEXEC: c_int = 0x40000000;
pub const MSG_CONFIRM: c_int = 0x800;
pub const MSG_CTRUNC: c_int = 0x0020;
pub const MSG_DONTROUTE: c_int = 0x0004;
pub const MSG_DONTWAIT: c_int = 0x0080;
pub const MSG_EOR: c_int = 0x0008;
pub const MSG_ERRQUEUE: c_int = 0x2000;
pub const MSG_MORE: c_int = 0x8000;
pub const MSG_NOSIGNAL: c_int = 1024;
pub const MSG_OOB: c_int = 0x0001;
pub const MSG_PEEK: c_int = 0x0002;
pub const MSG_TRUNC: c_int = 0x0010;
pub const MSG_WAITALL: c_int = 0x0040;
pub const O_ACCMODE: c_int = 0x3;
pub const O_ASYNC: c_int = 0x40;
pub const O_DIRECT: c_int = 0x8000000;
pub const O_DSYNC: c_int = 0o000020;
pub const O_NOCTTY: c_int = 0o004000;
pub const O_SYNC: c_int = 0x80;
pub const PIPE_BUF: usize = 512;
pub const POSIX_FADV_DONTNEED: c_int = 4;
pub const POSIX_FADV_NOREUSE: c_int = 5;
pub const POSIX_FADV_NORMAL: c_int = 0;
pub const POSIX_FADV_RANDOM: c_int = 2;
pub const POSIX_FADV_SEQUENTIAL: c_int = 1;
pub const POSIX_FADV_WILLNEED: c_int = 3;
pub const PRIO_PGRP: c_int = 1;
pub const PRIO_PROCESS: c_int = 0;
pub const PRIO_USER: c_int = 2;
pub const P_ALL: idtype_t = 0;
pub const P_PGID: idtype_t = 2;
pub const P_PID: idtype_t = 1;
pub const RLIM_INFINITY: crate::rlim_t = 0xfffffffffffffffd;
pub const R_OK: c_int = 4;
pub const SCM_RIGHTS: c_int = 0x01;
pub const SEEK_CUR: c_int = 1;
pub const SEEK_END: c_int = 2;
pub const SEEK_SET: c_int = 0;
pub const SHUT_RD: c_int = 0;
pub const SHUT_RDWR: c_int = 2;
pub const SHUT_WR: c_int = 1;
pub const SIGABRT: c_int = 6;
pub const SIGALRM: c_int = 14;
pub const SIGBUS: c_int = 10;
pub const SIGCHLD: c_int = 20;
pub const SIGCONT: c_int = 19;
pub const SIGFPE: c_int = 8;
pub const SIGHUP: c_int = 1;
pub const SIGILL: c_int = 4;
pub const SIGINT: c_int = 2;
pub const SIGIO: c_int = 23;
pub const SIGKILL: c_int = 9;
pub const SIGPIPE: c_int = 13;
pub const SIGPROF: c_int = 27;
pub const SIGPWR: c_int = 19;
pub const SIGQUIT: c_int = 3;
pub const SIGSEGV: c_int = 11;
pub const SIGSTKFLT: c_int = 16;
pub const SIGSTOP: c_int = 17;
pub const SIGSYS: c_int = 12;
pub const SIGTERM: c_int = 15;
pub const SIGTRAP: c_int = 5;
pub const SIGTSTP: c_int = 18;
pub const SIGTTIN: c_int = 21;
pub const SIGTTOU: c_int = 22;
pub const SIGURG: c_int = 16;
pub const SIGUSR1: c_int = 30;
pub const SIGUSR2: c_int = 31;
pub const SIGVTALRM: c_int = 26;
pub const SIGWINCH: c_int = 28;
pub const SIGXCPU: c_int = 24;
pub const SIGXFSZ: c_int = 25;
pub const SOCK_CLOEXEC: c_int = 0x10000000;
pub const SOCK_DGRAM: c_int = 2;
pub const SOCK_NONBLOCK: c_int = 2048;
pub const SOCK_RAW: c_int = 3;
pub const SOCK_RDM: c_int = 4;
pub const SOCK_SEQPACKET: c_int = 5;
pub const SOCK_STREAM: c_int = 1;
pub const SOL_SOCKET: c_int = 0xffff;
pub const SO_ACCEPTCONN: c_int = 0x0002;
pub const SO_BROADCAST: c_int = 0x0020;
pub const SO_DOMAIN: c_int = 39;
pub const SO_ERROR: c_int = 0x1007;
pub const SO_KEEPALIVE: c_int = 0x0008;
pub const SO_LINGER: c_int = 0x0080;
pub const SO_OOBINLINE: c_int = 0x0100;
pub const SO_RCVBUF: c_int = 0x1002;
pub const SO_RCVTIMEO: c_int = 0x1006;
pub const SO_REUSEADDR: c_int = 0x0004;
pub const SO_REUSEPORT: c_int = 0x0200;
pub const SO_SNDBUF: c_int = 0x1001;
pub const SO_SNDTIMEO: c_int = 0x1005;
pub const SO_TYPE: c_int = 0x1008;
pub const ST_NOSUID: c_ulong = 0x04;
pub const ST_RDONLY: c_ulong = 1;
pub const S_IFBLK: mode_t = 0o6_0000;
pub const S_IFCHR: mode_t = 0o2_0000;
pub const S_IFIFO: mode_t = 0o1_0000;
pub const S_IFSOCK: mode_t = 0o14_0000;
pub const S_IRGRP: mode_t = 0o0040;
pub const S_IROTH: mode_t = 0o0004;
pub const S_IRUSR: mode_t = 0o0400;
pub const S_IRWXG: mode_t = 0o0070;
pub const S_IRWXO: mode_t = 0o0007;
pub const S_IRWXU: mode_t = 0o0700;
pub const S_ISGID: mode_t = 0o2000;
pub const S_ISUID: mode_t = 0o4000;
pub const S_ISVTX: mode_t = 0o1000;
pub const S_IWGRP: mode_t = 0o0020;
pub const S_IWOTH: mode_t = 0o0002;
pub const S_IWUSR: mode_t = 0o0200;
pub const S_IXGRP: mode_t = 0o0010;
pub const S_IXOTH: mode_t = 0o0001;
pub const S_IXUSR: mode_t = 0o0100;
pub const TCP_KEEPCNT: c_int = 6;
pub const TCP_KEEPIDLE: c_int = 4;
pub const TCP_KEEPINTVL: c_int = 5;
pub const TCP_NODELAY: c_int = 1;
pub const TIOCSCTTY: c_int = 29793;
pub const UTIME_NOW: c_long = 0x40000001;
pub const UTIME_OMIT: c_long = 0x40000002;
pub const WCONTINUED: c_int = 0x0008;
pub const WEXITED: c_int = 0x0001;
pub const WNOHANG: c_int = 0x00000001;
pub const WNOWAIT: c_int = 0x0080;
pub const WSTOPPED: c_int = WUNTRACED;
pub const WUNTRACED: c_int = 0x00000002;
pub const W_OK: c_int = 2;
pub const X_OK: c_int = 1;
pub const _SC_CLK_TCK: c_int = 3;
pub const _SC_PAGESIZE: c_int = 11;
pub const AF_LOCAL: c_int = 1;
pub const AF_UNIX: c_int = 1;
pub const RTLD_DEFAULT: *mut c_void = core::ptr::null_mut();
pub const DT_CHR: c_uchar = 2;
pub const DT_FIFO: c_uchar = 1;
pub const DT_SOCK: c_uchar = 12;
pub const RLIMIT_CPU: c_int = 0;
pub const RLIMIT_FSIZE: c_int = 1;
pub const RLIMIT_DATA: c_int = 2;
pub const RLIMIT_STACK: c_int = 3;
pub const RLIMIT_CORE: c_int = 4;
pub const RLIMIT_RSS: c_int = 5;
pub const RLIMIT_NPROC: c_int = 6;
pub const RLIMIT_NOFILE: c_int = 7;
pub const RLIMIT_MEMLOCK: c_int = 8;
pub const RLIMIT_AS: c_int = 9;
pub const RLIMIT_LOCKS: c_int = 10;
pub const RLIMIT_SIGPENDING: c_int = 11;
pub const RLIMIT_MSGQUEUE: c_int = 12;
pub const RLIMIT_NICE: c_int = 13;
pub const RLIMIT_RTPRIO: c_int = 14;
pub const RLIMIT_RTTIME: __rlimit_resource_t = 15;

pub unsafe fn sync() {}
pub unsafe fn dlsym(_handle: *mut c_void, _symbol: *const c_char) -> *mut c_void {
    syscalls::set_errno(ENOSYS);
    core::ptr::null_mut()
}
pub unsafe fn fdopendir(_fd: c_int) -> *mut DIR {
    syscalls::set_errno(ENOSYS);
    core::ptr::null_mut()
}
pub unsafe fn readdir(_dirp: *mut DIR) -> *mut dirent {
    syscalls::set_errno(ENOSYS);
    core::ptr::null_mut()
}
pub unsafe fn rewinddir(_dirp: *mut DIR) {}
pub unsafe fn seekdir(_dirp: *mut DIR, _loc: c_long) {
    let _ = _dirp;
}

safe_f! {
    pub const safe fn major(dev: dev_t) -> c_uint {
        ((dev >> 8) & 0xfff) as c_uint | ((dev >> 32) & !0xfff) as c_uint
    }
    pub const safe fn minor(dev: dev_t) -> c_uint {
        (dev & 0xff) as c_uint | ((dev >> 12) & !0xff) as c_uint
    }
    pub const safe fn makedev(major: c_uint, minor: c_uint) -> dev_t {
        ((major & 0xfff) as dev_t) << 8
            | ((major & !0xfff) as dev_t) << 32
            | ((minor & 0xff) as dev_t)
            | ((minor & !0xff) as dev_t) << 12
    }

    pub const safe fn WIFSTOPPED(status: c_int) -> bool {
        (status & 0xff) == 0x7f
    }
    pub const safe fn WSTOPSIG(status: c_int) -> c_int {
        (status >> 8) & 0xff
    }
    pub const safe fn WIFCONTINUED(status: c_int) -> bool {
        status == 0xffff
    }
    pub const safe fn WIFSIGNALED(status: c_int) -> bool {
        ((status & 0x7f) + 1) as i8 >= 2
    }
    pub const safe fn WTERMSIG(status: c_int) -> c_int {
        status & 0x7f
    }
    pub const safe fn WIFEXITED(status: c_int) -> bool {
        (status & 0x7f) == 0
    }
    pub const safe fn WEXITSTATUS(status: c_int) -> c_int {
        (status >> 8) & 0xff
    }
}

// ENOSYS stubs for rustix-referenced libc functions.
enosys! {
    pub unsafe fn accept(fd: c_int, addr: *mut sockaddr, addrlen: *mut socklen_t) -> c_int;
    pub unsafe fn accept4(fd: c_int, addr: *mut sockaddr, addrlen: *mut socklen_t, flags: c_int) -> c_int;
    pub unsafe fn bind(fd: c_int, addr: *const sockaddr, len: socklen_t) -> c_int;
    pub unsafe fn chroot(path: *const c_char) -> c_int;
    pub unsafe fn clock_getres(clk: clockid_t, tp: *mut timespec) -> c_int;
    pub unsafe fn clock_settime(clk: clockid_t, tp: *const timespec) -> c_int;
    pub unsafe fn closedir(dirp: *mut DIR) -> c_int;
    pub unsafe fn connect(fd: c_int, addr: *const sockaddr, len: socklen_t) -> c_int;
    pub unsafe fn dirfd(dirp: *mut DIR) -> c_int;
    pub unsafe fn dup3(oldfd: c_int, newfd: c_int, flags: c_int) -> c_int;
    pub unsafe fn fchdir(fd: c_int) -> c_int;
    pub unsafe fn fchmodat(dirfd: c_int, path: *const c_char, mode: mode_t, flags: c_int) -> c_int;
    pub unsafe fn fchownat(dirfd: c_int, path: *const c_char, owner: uid_t, group: gid_t, flags: c_int) -> c_int;
    pub unsafe fn flock(fd: c_int, operation: c_int) -> c_int;
    pub unsafe fn fstatfs(fd: c_int, buf: *mut statfs) -> c_int;
    pub unsafe fn fstatvfs(fd: c_int, buf: *mut statvfs) -> c_int;
    pub unsafe fn futimens(fd: c_int, times: *const timespec) -> c_int;
    pub unsafe fn getgroups(size: c_int, list: *mut gid_t) -> c_int;
    pub unsafe fn getpeername(fd: c_int, addr: *mut sockaddr, len: *mut socklen_t) -> c_int;
    pub unsafe fn getpgid(pid: pid_t) -> pid_t;
    pub unsafe fn getpgrp() -> pid_t;
    pub unsafe fn getppid() -> pid_t;
    pub unsafe fn getpriority(which: c_int, who: c_int) -> c_int;
    pub unsafe fn getrlimit(resource: c_int, rlim: *mut rlimit) -> c_int;
    pub unsafe fn getsid(pid: pid_t) -> pid_t;
    pub unsafe fn getsockname(fd: c_int, addr: *mut sockaddr, len: *mut socklen_t) -> c_int;
    pub unsafe fn getsockopt(fd: c_int, level: c_int, optname: c_int, optval: *mut c_void, optlen: *mut socklen_t) -> c_int;
    pub unsafe fn listen(fd: c_int, backlog: c_int) -> c_int;
    pub unsafe fn mknodat(dirfd: c_int, path: *const c_char, mode: mode_t, dev: dev_t) -> c_int;
    pub unsafe fn nice(inc: c_int) -> c_int;
    pub unsafe fn posix_fadvise(fd: c_int, offset: off_t, len: off_t, advice: c_int) -> c_int;
    pub unsafe fn posix_fallocate(fd: c_int, offset: off_t, len: off_t) -> c_int;
    pub unsafe fn preadv(fd: c_int, iov: *const iovec, iovcnt: c_int, offset: off_t) -> ssize_t;
    pub unsafe fn pwritev(fd: c_int, iov: *const iovec, iovcnt: c_int, offset: off_t) -> ssize_t;
    pub unsafe fn recv(fd: c_int, buf: *mut c_void, len: size_t, flags: c_int) -> ssize_t;
    pub unsafe fn recvfrom(fd: c_int, buf: *mut c_void, len: size_t, flags: c_int, addr: *mut sockaddr, addrlen: *mut socklen_t) -> ssize_t;
    pub unsafe fn recvmsg(fd: c_int, msg: *mut msghdr, flags: c_int) -> ssize_t;
    pub unsafe fn send(fd: c_int, buf: *const c_void, len: size_t, flags: c_int) -> ssize_t;
    pub unsafe fn sendmsg(fd: c_int, msg: *const msghdr, flags: c_int) -> ssize_t;
    pub unsafe fn sendto(fd: c_int, buf: *const c_void, len: size_t, flags: c_int, addr: *const sockaddr, addrlen: socklen_t) -> ssize_t;
    pub unsafe fn setpgid(pid: pid_t, pgid: pid_t) -> c_int;
    pub unsafe fn setpriority(which: c_int, who: c_int, prio: c_int) -> c_int;
    pub unsafe fn setrlimit(resource: c_int, rlim: *const rlimit) -> c_int;
    pub unsafe fn setsid() -> pid_t;
    pub unsafe fn setsockopt(fd: c_int, level: c_int, optname: c_int, optval: *const c_void, optlen: socklen_t) -> c_int;
    pub unsafe fn shutdown(fd: c_int, how: c_int) -> c_int;
    pub unsafe fn socket(domain: c_int, ty: c_int, protocol: c_int) -> c_int;
    pub unsafe fn socketpair(domain: c_int, ty: c_int, protocol: c_int, sv: *mut c_int) -> c_int;
    pub unsafe fn statfs(path: *const c_char, buf: *mut statfs) -> c_int;
    pub unsafe fn statvfs(path: *const c_char, buf: *mut statvfs) -> c_int;
    pub unsafe fn sysconf(name: c_int) -> c_long;
    pub unsafe fn umask(mask: mode_t) -> mode_t;
    pub unsafe fn waitid(idtype: idtype_t, id: c_int, infop: *mut siginfo_t, options: c_int) -> c_int;
}
